[package]
name = "artificialeaselsolutionsultra"
version = "0.1.0"
edition = "2021"
authors = ["ezozu"]
description = "ArtificialEaselSolutionsUltra implementation in Rust"
license = "MIT"

[dependencies]
log = "0.4"
env_logger = "0.10"
clap = { version = "4.0", features = ["derive"] }
